module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: { '^.+\\.tsx?$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.test.json' }] },
  roots: ['<rootDir>/apps/backend/src', '<rootDir>/apps/frontend/src', '<rootDir>/shared/src'],
  testMatch: ['**/*.spec.ts'],
  moduleNameMapper: { '^dova-shared$': '<rootDir>/shared/src/index.ts' },
  setupFiles: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'apps/backend/src/**/*.ts',
    'apps/frontend/src/lib/**/*.ts',
    'shared/src/**/*.ts',
    '!**/*.d.ts',
    '!**/main.ts',
    '!**/*.spec.ts',
    '!**/*.test-doubles.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  clearMocks: true,
};
