import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { Pool } from 'pg';
import * as bcrypt from 'bcryptjs';
import { createHash } from 'crypto';
import { Cart, Category, Order, Product, Role, User } from 'dova-shared';

export type StoredUser = User & { passwordHash: string };
const digest = (value: string) => createHash('sha256').update(value).digest('hex');

@Injectable()
export class DatabaseService implements OnModuleInit, OnModuleDestroy {
  readonly enabled = Boolean(process.env.DATABASE_URL) && process.env.USE_IN_MEMORY !== 'true';
  readonly pool?: Pool;
  constructor() { if (this.enabled) this.pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 10 }); }
  async onModuleInit() { if (!this.pool) return; await this.pool.query('SELECT 1'); await this.bootstrap(); }
  async onModuleDestroy() { await this.pool?.end(); }
  private mapUser(row: any): StoredUser { return { id: row.id, email: row.email, fullName: row.full_name, phoneNumber: row.phone_number || undefined, role: row.role as Role, isActive: row.is_active, createdAt: new Date(row.created_at).toISOString(), passwordHash: row.password_hash }; }
  async findUserByEmail(email: string) { if (!this.pool) return undefined; const result = await this.pool.query('SELECT * FROM users WHERE email = $1 LIMIT 1', [email.toLowerCase()]); return result.rows[0] ? this.mapUser(result.rows[0]) : undefined; }
  async findUserById(id: string) { if (!this.pool) return undefined; const result = await this.pool.query('SELECT * FROM users WHERE id = $1 LIMIT 1', [id]); return result.rows[0] ? this.mapUser(result.rows[0]) : undefined; }
  async insertUser(user: StoredUser) { if (!this.pool) return; await this.pool.query('INSERT INTO users (id,email,password_hash,full_name,role,is_active,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$7)', [user.id, user.email, user.passwordHash, user.fullName, user.role, user.isActive, user.createdAt]); }
  async saveSession(userId: string, refreshToken: string, expiresAt: Date) { if (!this.pool) return; await this.pool.query('INSERT INTO user_sessions (user_id,token_hash,expires_at) VALUES ($1,$2,$3)', [userId, digest(refreshToken), expiresAt]); }
  async hasSession(userId: string, refreshToken: string) { if (!this.pool) return true; const result = await this.pool.query('SELECT 1 FROM user_sessions WHERE user_id=$1 AND token_hash=$2 AND expires_at > NOW() LIMIT 1', [userId, digest(refreshToken)]); return result.rowCount === 1; }
  async revokeSession(refreshToken?: string) { if (this.pool && refreshToken) await this.pool.query('DELETE FROM user_sessions WHERE token_hash=$1', [digest(refreshToken)]); }
  private mapProduct(row: any): Product { return { id: row.id, supplierId: row.supplier_id, supplierName: row.business_name, name: row.name, description: row.description || '', price: Number(row.price), stockQuantity: row.stock_quantity, categoryId: row.category_id, categoryName: row.category_name, imageUrl: row.image_url || undefined, isActive: row.is_active }; }
  async listProducts(search = '', categoryId = '', page = 1, limit = 20) { if (!this.pool) return undefined; const values: unknown[] = []; const filters = ['p.is_active = TRUE']; if (search) { values.push(`%${search.toLowerCase()}%`); filters.push(`LOWER(p.name) LIKE $${values.length}`); } if (categoryId) { values.push(categoryId); filters.push(`p.category_id = $${values.length}`); } const where = filters.join(' AND '); const totalResult = await this.pool.query(`SELECT COUNT(*)::int AS total FROM products p WHERE ${where}`, values); values.push(limit, (page - 1) * limit); const result = await this.pool.query(`SELECT p.*, s.business_name, c.name AS category_name FROM products p JOIN supplier_profiles s ON s.id=p.supplier_id JOIN categories c ON c.id=p.category_id WHERE ${where} ORDER BY p.created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values); return { data: result.rows.map(row => this.mapProduct(row)), pagination: { page, limit, total: totalResult.rows[0].total } }; }
  async findProduct(id: string) { if (!this.pool) return undefined; const result = await this.pool.query('SELECT p.*, s.business_name, c.name AS category_name FROM products p JOIN supplier_profiles s ON s.id=p.supplier_id JOIN categories c ON c.id=p.category_id WHERE p.id=$1 AND p.is_active=TRUE', [id]); return result.rows[0] ? this.mapProduct(result.rows[0]) : undefined; }
  async categories() { if (!this.pool) return undefined; const result = await this.pool.query('SELECT id,name FROM categories ORDER BY name'); return result.rows as Category[]; }
  async getCart(userId: string) { if (!this.pool) return undefined; const result = await this.pool.query('SELECT ci.id,ci.quantity,p.*,s.business_name,c.name AS category_name FROM carts ca JOIN cart_items ci ON ci.cart_id=ca.id JOIN products p ON p.id=ci.product_id JOIN supplier_profiles s ON s.id=p.supplier_id JOIN categories c ON c.id=p.category_id WHERE ca.user_id=$1 AND p.is_active=TRUE', [userId]); const items = result.rows.map(row => ({ id: row.id, product: this.mapProduct(row), quantity: row.quantity, subtotal: Number(row.price) * row.quantity })); return { items, total: items.reduce((sum, item) => sum + item.subtotal, 0) } as Cart; }
  async saveCart(userId: string, cart: Cart) { if (!this.pool) return; const client = await this.pool.connect(); try { await client.query('BEGIN'); const cartResult = await client.query('INSERT INTO carts (user_id) VALUES ($1) ON CONFLICT (user_id) DO UPDATE SET updated_at=NOW() RETURNING id', [userId]); const cartId = cartResult.rows[0].id; await client.query('DELETE FROM cart_items WHERE cart_id=$1', [cartId]); for (const item of cart.items) await client.query('INSERT INTO cart_items (id,cart_id,product_id,quantity) VALUES ($1,$2,$3,$4)', [item.id, cartId, item.product.id, item.quantity]); await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async createOrderFromCart(userId: string, body: any) { if (!this.pool) return undefined; const client = await this.pool.connect(); try { await client.query('BEGIN'); const result = await client.query('SELECT ci.id,ci.quantity,p.*,s.business_name,c.name AS category_name FROM carts ca JOIN cart_items ci ON ci.cart_id=ca.id JOIN products p ON p.id=ci.product_id JOIN supplier_profiles s ON s.id=p.supplier_id JOIN categories c ON c.id=p.category_id WHERE ca.user_id=$1 FOR UPDATE', [userId]); if (!result.rows.length) throw new Error('Cart is empty'); if (!body.deliveryName || !body.deliveryAddress || !body.deliveryPhone) throw new Error('Delivery details are required'); const items = result.rows.map(row => ({ id: row.id, product: this.mapProduct(row), quantity: row.quantity, subtotal: Number(row.price) * row.quantity })); if (items.some(item => item.quantity > item.product.stockQuantity)) throw new Error('Quantity exceeds available stock'); const total = items.reduce((sum, item) => sum + item.subtotal, 0); const orderResult = await client.query('INSERT INTO orders (customer_id,order_number,status,total_amount,delivery_name,delivery_address,delivery_phone) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [userId, `DOVA-${Date.now().toString(36).toUpperCase()}`, 'pending', total, body.deliveryName, body.deliveryAddress, body.deliveryPhone]); const row = orderResult.rows[0]; for (const item of items) { await client.query('UPDATE products SET stock_quantity=stock_quantity-$1,updated_at=NOW() WHERE id=$2', [item.quantity, item.product.id]); await client.query('INSERT INTO order_items (id,order_id,product_id,supplier_id,quantity,unit_price,subtotal) VALUES ($1,$2,$3,$4,$5,$6,$7)', [item.id,row.id,item.product.id,item.product.supplierId,item.quantity,item.product.price,item.subtotal]); } await client.query('DELETE FROM cart_items WHERE cart_id=(SELECT id FROM carts WHERE user_id=$1)', [userId]); await client.query('COMMIT'); return { id: row.id, orderNumber: row.order_number, customerId: row.customer_id, status: row.status, totalAmount: Number(row.total_amount), deliveryName: row.delivery_name, deliveryAddress: row.delivery_address, deliveryPhone: row.delivery_phone, items: items.map(item => ({ id: item.id, product: item.product, quantity: item.quantity, unitPrice: item.product.price, subtotal: item.subtotal, supplierOrderStatus: 'pending' })), createdAt: new Date(row.created_at).toISOString() } as Order; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async listOrders(userId: string) { if (!this.pool) return undefined; const result = await this.pool.query('SELECT * FROM orders WHERE customer_id=$1 ORDER BY created_at DESC', [userId]); const orders: Order[] = []; for (const row of result.rows) { const itemResult = await this.pool.query('SELECT oi.*,p.*,s.business_name,c.name AS category_name FROM order_items oi JOIN products p ON p.id=oi.product_id JOIN supplier_profiles s ON s.id=oi.supplier_id JOIN categories c ON c.id=p.category_id WHERE oi.order_id=$1 ORDER BY oi.created_at', [row.id]); orders.push({ id: row.id, orderNumber: row.order_number, customerId: row.customer_id, status: row.status, totalAmount: Number(row.total_amount), deliveryName: row.delivery_name, deliveryAddress: row.delivery_address, deliveryPhone: row.delivery_phone, paymentReference: row.payment_reference || undefined, paymentVerifiedAt: row.payment_verified_at ? new Date(row.payment_verified_at).toISOString() : undefined, items: itemResult.rows.map(item => ({ id: item.id, product: this.mapProduct(item), quantity: item.quantity, unitPrice: Number(item.unit_price), subtotal: Number(item.subtotal), supplierOrderStatus: item.supplier_order_status })), createdAt: new Date(row.created_at).toISOString() }); } return orders; }
  async findOrder(userId: string, orderId: string) { const orders = await this.listOrders(userId); return orders?.find(order => order.id === orderId); }
  async markOrderPaid(orderId: string, reference: string) { if (this.pool) await this.pool.query("UPDATE orders SET status='paid',payment_reference=$1,payment_verified_at=NOW(),updated_at=NOW() WHERE id=$2", [reference, orderId]); }
  async setOrderPaymentReference(orderId: string, reference: string) { if (this.pool) await this.pool.query('UPDATE orders SET payment_reference=$1,updated_at=NOW() WHERE id=$2', [reference, orderId]); }
  async logPayment(orderId: string, reference: string, amount: number, status: string, response?: unknown) { if (this.pool) await this.pool.query('INSERT INTO payment_logs (order_id,payment_reference,amount,status,paystack_response) VALUES ($1,$2,$3,$4,$5)', [orderId, reference, amount, status, response ? JSON.stringify(response) : null]); }
  private async bootstrap() { if (!this.pool) return; const adminPassword = bcrypt.hashSync(process.env.ADMIN_PASSWORD ?? 'admin1234', 12); await this.pool.query(`INSERT INTO users (email,password_hash,full_name,role) VALUES ('admin@dova.local',$1,'DOVA Admin','admin') ON CONFLICT (email) DO NOTHING`, [adminPassword]); }
}
